// ============================================================================
// INITIAL SEED DATA
// Realistic sample data for all entities
// ============================================================================

import {
  Strain, Location, Vessel, ContainerType, SubstrateType, Supplier,
  InventoryCategory, InventoryItem, Culture, Grow, Recipe, AppSettings,
  DataStoreState
} from './types';

// ============================================================================
// STRAINS
// ============================================================================

export const initialStrains: Strain[] = [
  {
    id: 'strain-001',
    name: 'B+',
    species: 'cubensis',
    difficulty: 'beginner',
    colonizationDays: { min: 10, max: 14 },
    fruitingDays: { min: 7, max: 14 },
    optimalTempColonization: { min: 24, max: 27 },
    optimalTempFruiting: { min: 21, max: 24 },
    notes: 'Excellent beginner strain, resilient and forgiving',
    isActive: true,
  },
  {
    id: 'strain-002',
    name: 'Golden Teacher',
    species: 'cubensis',
    difficulty: 'beginner',
    colonizationDays: { min: 10, max: 14 },
    fruitingDays: { min: 7, max: 14 },
    optimalTempColonization: { min: 24, max: 27 },
    optimalTempFruiting: { min: 21, max: 24 },
    notes: 'Classic strain, great for learning',
    isActive: true,
  },
  {
    id: 'strain-003',
    name: 'Penis Envy',
    species: 'cubensis',
    difficulty: 'advanced',
    colonizationDays: { min: 14, max: 21 },
    fruitingDays: { min: 10, max: 18 },
    optimalTempColonization: { min: 25, max: 28 },
    optimalTempFruiting: { min: 22, max: 25 },
    notes: 'Slower colonization, requires patience',
    isActive: true,
  },
  {
    id: 'strain-004',
    name: 'JMF',
    species: 'cubensis',
    difficulty: 'intermediate',
    colonizationDays: { min: 10, max: 14 },
    fruitingDays: { min: 7, max: 12 },
    optimalTempColonization: { min: 24, max: 27 },
    optimalTempFruiting: { min: 21, max: 24 },
    notes: 'Aggressive colonizer, good yields',
    isActive: true,
  },
  {
    id: 'strain-005',
    name: 'Blue Oyster',
    species: 'oyster',
    difficulty: 'beginner',
    colonizationDays: { min: 7, max: 14 },
    fruitingDays: { min: 5, max: 10 },
    optimalTempColonization: { min: 20, max: 24 },
    optimalTempFruiting: { min: 15, max: 21 },
    notes: 'Fast growing, needs lots of fresh air',
    isActive: true,
  },
  {
    id: 'strain-006',
    name: 'Lions Mane',
    species: 'lions_mane',
    difficulty: 'intermediate',
    colonizationDays: { min: 14, max: 21 },
    fruitingDays: { min: 7, max: 14 },
    optimalTempColonization: { min: 21, max: 24 },
    optimalTempFruiting: { min: 18, max: 22 },
    notes: 'Medicinal mushroom, needs high humidity',
    isActive: true,
  },
  {
    id: 'strain-007',
    name: 'Pink Oyster',
    species: 'oyster',
    difficulty: 'beginner',
    colonizationDays: { min: 7, max: 10 },
    fruitingDays: { min: 4, max: 7 },
    optimalTempColonization: { min: 24, max: 30 },
    optimalTempFruiting: { min: 21, max: 29 },
    notes: 'Tropical variety, likes warmth',
    isActive: true,
  },
  {
    id: 'strain-008',
    name: 'Shiitake',
    species: 'shiitake',
    difficulty: 'intermediate',
    colonizationDays: { min: 60, max: 120 },
    fruitingDays: { min: 7, max: 14 },
    optimalTempColonization: { min: 21, max: 27 },
    optimalTempFruiting: { min: 15, max: 21 },
    notes: 'Long colonization but excellent shelf life',
    isActive: true,
  },
];

// ============================================================================
// LOCATIONS
// ============================================================================

export const initialLocations: Location[] = [
  {
    id: 'loc-001',
    name: 'Incubation Chamber',
    type: 'incubation',
    tempRange: { min: 24, max: 28 },
    humidityRange: { min: 70, max: 80 },
    notes: 'Main incubation space with heating mat',
    isActive: true,
  },
  {
    id: 'loc-002',
    name: 'Fruiting Chamber',
    type: 'fruiting',
    tempRange: { min: 20, max: 24 },
    humidityRange: { min: 85, max: 95 },
    notes: 'Martha tent with humidifier',
    isActive: true,
  },
  {
    id: 'loc-003',
    name: 'Main Lab',
    type: 'lab',
    tempRange: { min: 20, max: 25 },
    notes: 'Clean work area with flow hood',
    isActive: true,
  },
  {
    id: 'loc-004',
    name: 'Lab Fridge',
    type: 'storage',
    tempRange: { min: 2, max: 6 },
    notes: 'Culture storage',
    isActive: true,
  },
  {
    id: 'loc-005',
    name: 'Supply Closet',
    type: 'storage',
    notes: 'Dry goods and supplies',
    isActive: true,
  },
  {
    id: 'loc-006',
    name: 'Garage',
    type: 'other',
    notes: 'Bulk pasteurization and bucket grows',
    isActive: true,
  },
];

// ============================================================================
// VESSELS
// ============================================================================

export const initialVessels: Vessel[] = [
  {
    id: 'vessel-001',
    name: 'Quart Mason Jar',
    type: 'jar',
    volumeMl: 946,
    isReusable: true,
    notes: 'Standard grain jar',
    isActive: true,
  },
  {
    id: 'vessel-002',
    name: 'Pint Mason Jar',
    type: 'jar',
    volumeMl: 473,
    isReusable: true,
    notes: 'Smaller grain/LC jar',
    isActive: true,
  },
  {
    id: 'vessel-003',
    name: '100mm Petri Dish',
    type: 'plate',
    volumeMl: 25,
    isReusable: false,
    notes: 'Standard agar plate',
    isActive: true,
  },
  {
    id: 'vessel-004',
    name: 'Test Tube Slant',
    type: 'tube',
    volumeMl: 15,
    isReusable: true,
    notes: 'Long-term storage',
    isActive: true,
  },
  {
    id: 'vessel-005',
    name: '500ml Media Bottle',
    type: 'bottle',
    volumeMl: 500,
    isReusable: true,
    notes: 'LC or agar media',
    isActive: true,
  },
  {
    id: 'vessel-006',
    name: '10cc Syringe',
    type: 'syringe',
    volumeMl: 10,
    isReusable: false,
    notes: 'Spore or LC syringe',
    isActive: true,
  },
  {
    id: 'vessel-007',
    name: '3lb Spawn Bag',
    type: 'bag',
    volumeMl: 2000,
    isReusable: false,
    notes: 'Grain spawn bag with filter patch',
    isActive: true,
  },
  {
    id: 'vessel-008',
    name: '5lb Spawn Bag',
    type: 'bag',
    volumeMl: 3500,
    isReusable: false,
    notes: 'Large grain spawn bag',
    isActive: true,
  },
];

// ============================================================================
// CONTAINER TYPES
// ============================================================================

export const initialContainerTypes: ContainerType[] = [
  {
    id: 'cont-001',
    name: '66qt Monotub',
    category: 'tub',
    volumeL: 62,
    dimensions: { length: 60, width: 40, height: 35 },
    notes: 'Standard monotub',
    isActive: true,
  },
  {
    id: 'cont-002',
    name: '6qt Shoebox',
    category: 'tub',
    volumeL: 5.7,
    dimensions: { length: 34, width: 21, height: 12 },
    notes: 'Small personal grow',
    isActive: true,
  },
  {
    id: 'cont-003',
    name: '5lb Grow Bag',
    category: 'bag',
    volumeL: 4,
    notes: 'All-in-one grow bag',
    isActive: true,
  },
  {
    id: 'cont-004',
    name: '5 Gallon Bucket',
    category: 'bucket',
    volumeL: 19,
    notes: 'Bucket tek container',
    isActive: true,
  },
  {
    id: 'cont-005',
    name: 'BRF Cake Jar',
    category: 'jar',
    volumeL: 0.5,
    notes: 'Half pint PF tek jar',
    isActive: true,
  },
  {
    id: 'cont-006',
    name: 'Outdoor Bed',
    category: 'bed',
    volumeL: 100,
    notes: 'Garden bed for wood lovers',
    isActive: true,
  },
];

// ============================================================================
// SUBSTRATE TYPES
// ============================================================================

export const initialSubstrateTypes: SubstrateType[] = [
  {
    id: 'sub-001',
    name: 'CVG (Coco/Verm/Gypsum)',
    code: 'cvg',
    category: 'bulk',
    spawnRateRange: { min: 10, optimal: 20, max: 30 },
    fieldCapacity: 75,
    notes: 'Standard cubensis substrate',
    isActive: true,
  },
  {
    id: 'sub-002',
    name: 'Manure-Based',
    code: 'manure',
    category: 'bulk',
    spawnRateRange: { min: 15, optimal: 25, max: 35 },
    fieldCapacity: 70,
    notes: 'Horse/cow manure with supplements',
    isActive: true,
  },
  {
    id: 'sub-003',
    name: 'Pasteurized Straw',
    code: 'straw',
    category: 'bulk',
    spawnRateRange: { min: 10, optimal: 15, max: 25 },
    fieldCapacity: 65,
    notes: 'Good for oysters and bucket tek',
    isActive: true,
  },
  {
    id: 'sub-004',
    name: 'Hardwood Sawdust',
    code: 'sawdust',
    category: 'bulk',
    spawnRateRange: { min: 15, optimal: 20, max: 30 },
    fieldCapacity: 65,
    notes: 'Oak, maple, beech sawdust',
    isActive: true,
  },
  {
    id: 'sub-005',
    name: "Master's Mix",
    code: 'masters_mix',
    category: 'bulk',
    spawnRateRange: { min: 10, optimal: 15, max: 25 },
    fieldCapacity: 60,
    notes: '50/50 hardwood sawdust and soy hulls',
    isActive: true,
  },
  {
    id: 'sub-006',
    name: 'Oat Groats',
    code: 'oat',
    category: 'grain',
    spawnRateRange: { min: 5, optimal: 10, max: 15 },
    notes: 'Whole oats for grain spawn',
    isActive: true,
  },
  {
    id: 'sub-007',
    name: 'Rye Berries',
    code: 'rye',
    category: 'grain',
    spawnRateRange: { min: 5, optimal: 10, max: 15 },
    notes: 'Premium grain spawn option',
    isActive: true,
  },
  {
    id: 'sub-008',
    name: 'Malt Extract Agar',
    code: 'mea',
    category: 'agar',
    spawnRateRange: { min: 0, optimal: 0, max: 0 },
    notes: 'Standard agar medium',
    isActive: true,
  },
  {
    id: 'sub-009',
    name: 'Potato Dextrose Agar',
    code: 'pda',
    category: 'agar',
    spawnRateRange: { min: 0, optimal: 0, max: 0 },
    notes: 'Alternative agar medium',
    isActive: true,
  },
  {
    id: 'sub-010',
    name: 'Honey Liquid Culture',
    code: 'honey_lc',
    category: 'liquid',
    spawnRateRange: { min: 0, optimal: 0, max: 0 },
    notes: '4% honey solution',
    isActive: true,
  },
];

// ============================================================================
// SUPPLIERS
// ============================================================================

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: 'Midwest Grow Kits',
    website: 'https://midwestgrowkits.com',
    notes: 'Substrate and supplies',
    isActive: true,
  },
  {
    id: 'sup-002',
    name: 'Shroomsupply',
    website: 'https://shroomsupply.com',
    notes: 'Lab supplies and equipment',
    isActive: true,
  },
  {
    id: 'sup-003',
    name: 'Amazon',
    website: 'https://amazon.com',
    notes: 'General supplies',
    isActive: true,
  },
  {
    id: 'sup-004',
    name: 'Local Farm Supply',
    notes: 'Grains and straw',
    isActive: true,
  },
  {
    id: 'sup-005',
    name: 'Fungi Perfecti',
    website: 'https://fungi.com',
    notes: 'Cultures and spawn',
    isActive: true,
  },
];

// ============================================================================
// INVENTORY CATEGORIES
// ============================================================================

export const initialInventoryCategories: InventoryCategory[] = [
  { id: 'cat-001', name: 'Grains', color: '#f59e0b', isActive: true },
  { id: 'cat-002', name: 'Substrates', color: '#84cc16', isActive: true },
  { id: 'cat-003', name: 'Lab Supplies', color: '#06b6d4', isActive: true },
  { id: 'cat-004', name: 'Containers', color: '#8b5cf6', isActive: true },
  { id: 'cat-005', name: 'Chemicals', color: '#ef4444', isActive: true },
  { id: 'cat-006', name: 'Equipment', color: '#6366f1', isActive: true },
  { id: 'cat-007', name: 'Media', color: '#ec4899', isActive: true },
];

// ============================================================================
// INVENTORY ITEMS
// ============================================================================

export const initialInventoryItems: InventoryItem[] = [
  {
    id: 'inv-001',
    name: 'Whole Oat Groats',
    categoryId: 'cat-001',
    quantity: 25,
    unit: 'lb',
    unitCost: 1.20,
    reorderPoint: 10,
    reorderQty: 50,
    supplierId: 'sup-004',
    locationId: 'loc-005',
    notes: 'Bulk oats for grain spawn',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-11-01'),
    isActive: true,
  },
  {
    id: 'inv-002',
    name: 'Rye Berries',
    categoryId: 'cat-001',
    quantity: 15,
    unit: 'lb',
    unitCost: 1.80,
    reorderPoint: 5,
    reorderQty: 25,
    supplierId: 'sup-004',
    locationId: 'loc-005',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-10-15'),
    isActive: true,
  },
  {
    id: 'inv-003',
    name: 'Coco Coir Brick',
    categoryId: 'cat-002',
    quantity: 8,
    unit: 'brick',
    unitCost: 4.50,
    reorderPoint: 3,
    reorderQty: 10,
    supplierId: 'sup-001',
    locationId: 'loc-005',
    notes: '650g compressed brick',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-09-20'),
    isActive: true,
  },
  {
    id: 'inv-004',
    name: 'Vermiculite (Coarse)',
    categoryId: 'cat-002',
    quantity: 4,
    unit: 'cu ft',
    unitCost: 18.00,
    reorderPoint: 1,
    reorderQty: 4,
    supplierId: 'sup-003',
    locationId: 'loc-005',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-08-15'),
    isActive: true,
  },
  {
    id: 'inv-005',
    name: 'Gypsum (calcium sulfate)',
    categoryId: 'cat-002',
    quantity: 5,
    unit: 'lb',
    unitCost: 3.00,
    reorderPoint: 2,
    reorderQty: 10,
    supplierId: 'sup-001',
    locationId: 'loc-005',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-07-10'),
    isActive: true,
  },
  {
    id: 'inv-006',
    name: 'Agar Powder',
    categoryId: 'cat-007',
    quantity: 500,
    unit: 'g',
    unitCost: 0.08,
    reorderPoint: 100,
    reorderQty: 500,
    supplierId: 'sup-002',
    locationId: 'loc-003',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
    isActive: true,
  },
  {
    id: 'inv-007',
    name: 'Light Malt Extract',
    categoryId: 'cat-007',
    quantity: 1000,
    unit: 'g',
    unitCost: 0.03,
    reorderPoint: 250,
    reorderQty: 1000,
    supplierId: 'sup-002',
    locationId: 'loc-003',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-05-15'),
    isActive: true,
  },
  {
    id: 'inv-008',
    name: 'Honey (raw)',
    categoryId: 'cat-007',
    quantity: 2000,
    unit: 'g',
    unitCost: 0.02,
    reorderPoint: 500,
    reorderQty: 2000,
    supplierId: 'sup-003',
    locationId: 'loc-003',
    notes: 'For liquid culture',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-04-01'),
    isActive: true,
  },
  {
    id: 'inv-009',
    name: '100mm Petri Dishes (sleeve)',
    categoryId: 'cat-003',
    quantity: 3,
    unit: 'sleeve (20)',
    unitCost: 12.00,
    reorderPoint: 1,
    reorderQty: 5,
    supplierId: 'sup-002',
    locationId: 'loc-003',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-01'),
    isActive: true,
  },
  {
    id: 'inv-010',
    name: 'Quart Mason Jars (case)',
    categoryId: 'cat-004',
    quantity: 2,
    unit: 'case (12)',
    unitCost: 15.00,
    reorderPoint: 1,
    reorderQty: 3,
    supplierId: 'sup-003',
    locationId: 'loc-005',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    isActive: true,
  },
  {
    id: 'inv-011',
    name: 'Isopropyl Alcohol 70%',
    categoryId: 'cat-005',
    quantity: 3,
    unit: 'gallon',
    unitCost: 15.00,
    reorderPoint: 1,
    reorderQty: 4,
    supplierId: 'sup-003',
    locationId: 'loc-003',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    isActive: true,
  },
  {
    id: 'inv-012',
    name: 'Micropore Tape',
    categoryId: 'cat-003',
    quantity: 6,
    unit: 'roll',
    unitCost: 4.00,
    reorderPoint: 2,
    reorderQty: 10,
    supplierId: 'sup-002',
    locationId: 'loc-003',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
    isActive: true,
  },
];

// ============================================================================
// CULTURES
// ============================================================================

export const initialCultures: Culture[] = [
  {
    id: 'culture-001',
    type: 'spore_syringe',
    label: 'SS-001',
    strainId: 'strain-001', // B+
    status: 'active',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-10-15'),
    generation: 0,
    locationId: 'loc-004', // Lab Fridge
    vesselId: 'vessel-006', // 10cc Syringe
    volumeMl: 7,
    healthRating: 5,
    notes: 'Original B+ spore syringe from Fungi Perfecti',
    cost: 15.00,
    supplierId: 'sup-005',
    lotNumber: 'FP-B+-2024-08',
    observations: [
      { id: 'obs-001', date: new Date('2024-08-01'), type: 'general', notes: 'Received, stored in fridge', healthRating: 5 },
    ],
    transfers: [
      { id: 'tr-001', date: new Date('2024-08-15'), fromId: 'culture-001', toId: 'culture-002', toType: 'agar', quantity: 1, unit: 'drop' },
    ],
  },
  {
    id: 'culture-002',
    type: 'agar',
    label: 'AG-001',
    strainId: 'strain-001', // B+
    status: 'ready',
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-09-01'),
    parentId: 'culture-001',
    generation: 1,
    locationId: 'loc-004',
    vesselId: 'vessel-003', // 100mm Petri Dish
    healthRating: 5,
    notes: 'Clean sector isolation from SS-001',
    cost: 2.00,
    observations: [
      { id: 'obs-002', date: new Date('2024-08-20'), type: 'growth', notes: 'Germination visible', healthRating: 4 },
      { id: 'obs-003', date: new Date('2024-09-01'), type: 'growth', notes: 'Full colonization, strong rhizo growth', healthRating: 5 },
    ],
    transfers: [
      { id: 'tr-002', date: new Date('2024-09-05'), fromId: 'culture-002', toId: 'culture-003', toType: 'agar', quantity: 1, unit: 'wedge' },
      { id: 'tr-003', date: new Date('2024-09-10'), fromId: 'culture-002', toId: 'culture-004', toType: 'liquid_culture', quantity: 1, unit: 'wedge' },
    ],
  },
  {
    id: 'culture-003',
    type: 'agar',
    label: 'AG-002',
    strainId: 'strain-001', // B+
    status: 'ready',
    createdAt: new Date('2024-09-05'),
    updatedAt: new Date('2024-09-20'),
    parentId: 'culture-002',
    generation: 2,
    locationId: 'loc-004',
    vesselId: 'vessel-003',
    healthRating: 5,
    notes: 'G2 transfer, excellent genetics',
    cost: 2.00,
    observations: [
      { id: 'obs-004', date: new Date('2024-09-20'), type: 'growth', notes: 'Full colonization', healthRating: 5 },
    ],
    transfers: [],
  },
  {
    id: 'culture-004',
    type: 'liquid_culture',
    label: 'LC-001',
    strainId: 'strain-001', // B+
    status: 'ready',
    createdAt: new Date('2024-09-10'),
    updatedAt: new Date('2024-10-01'),
    parentId: 'culture-002',
    generation: 2,
    locationId: 'loc-004',
    vesselId: 'vessel-001', // Quart Mason Jar
    volumeMl: 850,
    healthRating: 5,
    notes: 'Honey LC from AG-001, strong mycelial mass',
    cost: 5.00,
    observations: [
      { id: 'obs-005', date: new Date('2024-09-20'), type: 'growth', notes: 'Visible growth', healthRating: 4 },
      { id: 'obs-006', date: new Date('2024-10-01'), type: 'growth', notes: 'Heavy mycelial mass, ready for use', healthRating: 5 },
    ],
    transfers: [
      { id: 'tr-004', date: new Date('2024-10-15'), fromId: 'culture-004', toType: 'grain_spawn', quantity: 50, unit: 'ml', notes: 'Inoculated 3 quart jars' },
    ],
  },
  {
    id: 'culture-005',
    type: 'spore_syringe',
    label: 'SS-002',
    strainId: 'strain-003', // Penis Envy
    status: 'active',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-01'),
    generation: 0,
    locationId: 'loc-004',
    vesselId: 'vessel-006',
    volumeMl: 9,
    healthRating: 5,
    notes: 'PE spore syringe',
    cost: 20.00,
    supplierId: 'sup-005',
    observations: [],
    transfers: [
      { id: 'tr-005', date: new Date('2024-09-15'), fromId: 'culture-005', toId: 'culture-006', toType: 'agar', quantity: 1, unit: 'drop' },
    ],
  },
  {
    id: 'culture-006',
    type: 'liquid_culture',
    label: 'LC-002',
    strainId: 'strain-003', // Penis Envy
    status: 'colonizing',
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-11-01'),
    parentId: 'culture-005',
    generation: 1,
    locationId: 'loc-001', // Incubation
    vesselId: 'vessel-001',
    volumeMl: 500,
    healthRating: 4,
    notes: 'PE LC from spore syringe direct',
    cost: 5.00,
    observations: [
      { id: 'obs-007', date: new Date('2024-11-01'), type: 'growth', notes: 'Slow growth, typical for PE', healthRating: 4 },
    ],
    transfers: [],
  },
  {
    id: 'culture-007',
    type: 'slant',
    label: 'SL-001',
    strainId: 'strain-001', // B+
    status: 'archived',
    createdAt: new Date('2024-09-25'),
    updatedAt: new Date('2024-09-25'),
    parentId: 'culture-003',
    generation: 3,
    locationId: 'loc-004',
    vesselId: 'vessel-004', // Test Tube
    healthRating: 5,
    notes: 'Long-term storage of proven B+ genetics',
    cost: 1.00,
    observations: [],
    transfers: [],
  },
  {
    id: 'culture-008',
    type: 'agar',
    label: 'AG-003',
    strainId: 'strain-004', // JMF
    status: 'contaminated',
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-10'),
    generation: 1,
    locationId: 'loc-005', // Disposed
    vesselId: 'vessel-003',
    healthRating: 0,
    notes: 'Contaminated with bacteria',
    cost: 2.00,
    observations: [
      { id: 'obs-008', date: new Date('2024-10-10'), type: 'contamination', notes: 'Bacterial contamination visible', healthRating: 0 },
    ],
    transfers: [],
  },
];

// ============================================================================
// GROWS
// ============================================================================

export const initialGrows: Grow[] = [
  {
    id: 'grow-001',
    name: 'B+ Monotub #1',
    strainId: 'strain-001',
    status: 'active',
    currentStage: 'fruiting',
    sourceCultureId: 'culture-004', // LC-001
    spawnType: 'Oat Groats',
    spawnWeight: 900,
    substrateTypeId: 'sub-001', // CVG
    substrateWeight: 3600,
    spawnRate: 20,
    containerTypeId: 'cont-001', // 66qt Monotub
    containerCount: 1,
    createdAt: new Date('2024-10-25'),
    spawnedAt: new Date('2024-10-25'),
    colonizationStartedAt: new Date('2024-10-28'),
    fruitingStartedAt: new Date('2024-11-10'),
    firstPinsAt: new Date('2024-11-15'),
    firstHarvestAt: new Date('2024-11-20'),
    locationId: 'loc-002', // Fruiting Chamber
    targetTempColonization: 24,
    targetTempFruiting: 22,
    targetHumidity: 90,
    flushes: [
      { id: 'f1', flushNumber: 1, harvestDate: new Date('2024-11-20'), wetWeight: 450, dryWeight: 45, mushroomCount: 28, quality: 'excellent', notes: 'Great first flush!' },
      { id: 'f2', flushNumber: 2, harvestDate: new Date('2024-11-28'), wetWeight: 320, dryWeight: 32, mushroomCount: 22, quality: 'good' },
    ],
    totalYield: 77,
    estimatedCost: 15.50,
    observations: [
      { id: 'o1', date: new Date('2024-10-28'), stage: 'colonization', type: 'milestone', title: 'Colonization Started', notes: 'Visible mycelium growth at spawn points' },
      { id: 'o2', date: new Date('2024-11-05'), stage: 'colonization', type: 'general', title: '70% Colonized', notes: 'Strong rhizomorphic growth, no contam signs', colonizationPercent: 70 },
      { id: 'o3', date: new Date('2024-11-10'), stage: 'colonization', type: 'milestone', title: 'Full Colonization', notes: 'Surface fully colonized, introducing fruiting conditions', colonizationPercent: 100 },
      { id: 'o4', date: new Date('2024-11-15'), stage: 'fruiting', type: 'milestone', title: 'First Pins!', notes: 'Pinset forming across surface, good coverage' },
    ],
    notes: 'First B+ monotub grow, using CVG at field capacity',
  },
  {
    id: 'grow-002',
    name: 'PE Shoebox Run',
    strainId: 'strain-003',
    status: 'active',
    currentStage: 'colonization',
    sourceCultureId: 'culture-006', // LC-002
    spawnType: 'Rye Berries',
    spawnWeight: 400,
    substrateTypeId: 'sub-001',
    substrateWeight: 1200,
    spawnRate: 25,
    containerTypeId: 'cont-002', // Shoebox
    containerCount: 2,
    createdAt: new Date('2024-11-08'),
    spawnedAt: new Date('2024-11-08'),
    colonizationStartedAt: new Date('2024-11-12'),
    locationId: 'loc-001', // Incubation
    targetTempColonization: 25,
    targetTempFruiting: 23,
    targetHumidity: 90,
    flushes: [],
    totalYield: 0,
    estimatedCost: 12.00,
    observations: [
      { id: 'o5', date: new Date('2024-11-12'), stage: 'colonization', type: 'milestone', title: 'Growth Visible', notes: 'Slow but steady PE colonization beginning' },
      { id: 'o6', date: new Date('2024-11-18'), stage: 'colonization', type: 'general', title: '40% Colonized', notes: 'Typical PE speed, looking healthy', colonizationPercent: 40 },
    ],
    notes: 'PE takes longer but worth the wait',
  },
  {
    id: 'grow-003',
    name: 'JMF Experiment',
    strainId: 'strain-004',
    status: 'failed',
    currentStage: 'contaminated',
    spawnType: 'Popcorn',
    spawnWeight: 500,
    substrateTypeId: 'sub-001',
    substrateWeight: 2000,
    spawnRate: 20,
    containerTypeId: 'cont-001',
    containerCount: 1,
    createdAt: new Date('2024-10-15'),
    spawnedAt: new Date('2024-10-15'),
    colonizationStartedAt: new Date('2024-10-18'),
    completedAt: new Date('2024-10-28'),
    locationId: 'loc-006', // Disposed
    targetTempColonization: 24,
    targetTempFruiting: 22,
    targetHumidity: 90,
    flushes: [],
    totalYield: 0,
    estimatedCost: 14.00,
    observations: [
      { id: 'o7', date: new Date('2024-10-18'), stage: 'colonization', type: 'milestone', title: 'Colonization Started', notes: 'Normal start' },
      { id: 'o8', date: new Date('2024-10-25'), stage: 'colonization', type: 'contamination', title: 'Trichoderma Detected', notes: 'Green mold in corner, likely airborne contamination', colonizationPercent: 35 },
      { id: 'o9', date: new Date('2024-10-28'), stage: 'contaminated', type: 'milestone', title: 'Grow Aborted', notes: 'Contamination spread too far, disposed' },
    ],
    notes: 'Lost to trich - need to improve air filtration',
  },
  {
    id: 'grow-004',
    name: 'B+ Bucket Tek',
    strainId: 'strain-001',
    status: 'completed',
    currentStage: 'completed',
    sourceCultureId: 'culture-004',
    spawnType: 'Oat Groats',
    spawnWeight: 1500,
    substrateTypeId: 'sub-003', // Straw
    substrateWeight: 8000,
    spawnRate: 16,
    containerTypeId: 'cont-004', // Bucket
    containerCount: 1,
    createdAt: new Date('2024-09-20'),
    spawnedAt: new Date('2024-09-20'),
    colonizationStartedAt: new Date('2024-09-24'),
    fruitingStartedAt: new Date('2024-10-08'),
    firstPinsAt: new Date('2024-10-14'),
    firstHarvestAt: new Date('2024-10-18'),
    completedAt: new Date('2024-11-10'),
    locationId: 'loc-006', // Garage
    targetTempColonization: 24,
    targetTempFruiting: 20,
    targetHumidity: 85,
    flushes: [
      { id: 'f3', flushNumber: 1, harvestDate: new Date('2024-10-18'), wetWeight: 680, dryWeight: 68, quality: 'good' },
      { id: 'f4', flushNumber: 2, harvestDate: new Date('2024-10-28'), wetWeight: 520, dryWeight: 52, quality: 'good' },
      { id: 'f5', flushNumber: 3, harvestDate: new Date('2024-11-06'), wetWeight: 280, dryWeight: 28, quality: 'fair' },
    ],
    totalYield: 148,
    estimatedCost: 22.00,
    observations: [],
    notes: 'Straw bucket tek - low effort, decent yields',
  },
  {
    id: 'grow-005',
    name: 'Golden Teacher Bags',
    strainId: 'strain-002',
    status: 'active',
    currentStage: 'spawning',
    spawnType: 'Rye Berries',
    spawnWeight: 600,
    substrateTypeId: 'sub-005', // Master's Mix
    substrateWeight: 2400,
    spawnRate: 20,
    containerTypeId: 'cont-003', // Grow Bag
    containerCount: 3,
    createdAt: new Date('2024-11-15'),
    spawnedAt: new Date('2024-11-15'),
    locationId: 'loc-001', // Incubation
    targetTempColonization: 24,
    targetTempFruiting: 21,
    targetHumidity: 90,
    flushes: [],
    totalYield: 0,
    estimatedCost: 18.00,
    observations: [
      { id: 'o10', date: new Date('2024-11-15'), stage: 'spawning', type: 'milestone', title: 'Bags Inoculated', notes: 'S2B in all 3 bags, placed in incubation' },
    ],
    notes: 'Testing masters mix with GT genetics',
  },
];

// ============================================================================
// RECIPES
// ============================================================================

export const initialRecipes: Recipe[] = [
  {
    id: 'recipe-001',
    name: 'Standard CVG',
    category: 'bulk_substrate',
    description: 'Classic coco coir, vermiculite, and gypsum bulk substrate',
    yield: { amount: 10, unit: 'quarts' },
    prepTime: 30,
    sterilizationTime: 0, // Pasteurization only
    ingredients: [
      { id: 'ing-001', inventoryItemId: 'inv-003', name: 'Coco Coir Brick', quantity: 1, unit: 'brick' },
      { id: 'ing-002', inventoryItemId: 'inv-004', name: 'Vermiculite (Coarse)', quantity: 2, unit: 'quarts' },
      { id: 'ing-003', inventoryItemId: 'inv-005', name: 'Gypsum', quantity: 1, unit: 'cup' },
      { id: 'ing-004', name: 'Boiling Water', quantity: 4, unit: 'quarts' },
    ],
    instructions: [
      'Break up coco coir brick into a 5-gallon bucket',
      'Add vermiculite and gypsum, mix dry ingredients',
      'Pour boiling water over mixture',
      'Cover and let sit for 2-4 hours',
      'Mix thoroughly and check field capacity',
      'Squeeze test: should release a few drops of water',
      'Allow to cool to room temperature before use',
    ],
    tips: [
      'Field capacity is key - too wet promotes contamination',
      'Can pasteurize in oven at 160-180°F for 90 min as alternative',
    ],
    notes: 'Standard recipe for cubensis species',
    costPerBatch: 8.50,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    isActive: true,
  },
  {
    id: 'recipe-002',
    name: 'MEA (Malt Extract Agar)',
    category: 'agar',
    description: 'Standard malt extract agar for culture work',
    yield: { amount: 500, unit: 'ml' },
    prepTime: 15,
    sterilizationTime: 45,
    sterilizationPsi: 15,
    ingredients: [
      { id: 'ing-005', inventoryItemId: 'inv-006', name: 'Agar Powder', quantity: 10, unit: 'g' },
      { id: 'ing-006', inventoryItemId: 'inv-007', name: 'Light Malt Extract', quantity: 10, unit: 'g' },
      { id: 'ing-007', name: 'Distilled Water', quantity: 500, unit: 'ml' },
    ],
    instructions: [
      'Add agar and malt extract to distilled water',
      'Stir until dissolved (heating helps)',
      'Pour into media bottle or divide into petri dishes',
      'Cover with foil or parafilm',
      'Pressure cook at 15 PSI for 45 minutes',
      'Allow to cool slightly, then pour plates in front of flow hood',
      'Let plates solidify completely before storing',
    ],
    tips: [
      'Pour plates while agar is still liquid but not too hot (~50°C)',
      'Store plates upside down to prevent condensation on surface',
    ],
    notes: 'Makes approximately 20 plates',
    costPerBatch: 2.00,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    isActive: true,
  },
  {
    id: 'recipe-003',
    name: 'Honey Liquid Culture',
    category: 'liquid_culture',
    description: '4% honey solution for liquid culture',
    yield: { amount: 1000, unit: 'ml' },
    prepTime: 10,
    sterilizationTime: 30,
    sterilizationPsi: 15,
    ingredients: [
      { id: 'ing-008', inventoryItemId: 'inv-008', name: 'Honey (raw)', quantity: 40, unit: 'g' },
      { id: 'ing-009', name: 'Distilled Water', quantity: 1000, unit: 'ml' },
    ],
    instructions: [
      'Mix honey with distilled water until fully dissolved',
      'Pour into quart mason jars (leave headspace)',
      'Add magnetic stir bar if using stir plate',
      'Cover with modified lid (filter + injection port)',
      'Pressure cook at 15 PSI for 30 minutes',
      'Allow to cool completely before inoculating',
    ],
    tips: [
      'Use raw honey for best results',
      'Shake or stir daily to encourage growth',
      'LC is ready when you see fluffy mycelium clouds',
    ],
    notes: 'Simple and effective LC recipe',
    costPerBatch: 1.50,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    isActive: true,
  },
  {
    id: 'recipe-004',
    name: 'Oat Grain Spawn',
    category: 'grain_spawn',
    description: 'Whole oat groats for grain spawn production',
    yield: { amount: 1, unit: 'quart jar' },
    prepTime: 60,
    sterilizationTime: 90,
    sterilizationPsi: 15,
    ingredients: [
      { id: 'ing-010', inventoryItemId: 'inv-001', name: 'Whole Oat Groats', quantity: 1, unit: 'lb' },
      { id: 'ing-011', name: 'Water', quantity: 2, unit: 'quarts', notes: 'For soaking' },
    ],
    instructions: [
      'Rinse oats thoroughly to remove dust',
      'Soak oats in water for 12-24 hours',
      'Drain and rinse again',
      'Simmer for 15-20 minutes until slightly soft but not mushy',
      'Drain and spread on towels to dry surface moisture',
      'Load into jars with modified lids',
      'Pressure cook at 15 PSI for 90 minutes',
      'Allow to cool in PC, then shake to break up clumps',
    ],
    tips: [
      'Oats should crack when bitten but not be mushy',
      'Too wet = bacterial contamination',
      'Shake jars after cooling to prevent clumping',
    ],
    notes: 'Budget-friendly grain spawn option',
    costPerBatch: 3.00,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
    isActive: true,
  },
];

// ============================================================================
// APP SETTINGS
// ============================================================================

export const initialSettings: AppSettings = {
  defaultUnits: 'metric',
  defaultCurrency: 'USD',
  altitude: 0,
  timezone: 'America/Chicago',
  notifications: {
    enabled: true,
    harvestReminders: true,
    lowStockAlerts: true,
    contaminationAlerts: true,
  },
};

// ============================================================================
// COMBINED INITIAL STATE
// ============================================================================

// Default recipe categories
const initialRecipeCategories = [
  { id: 'default-agar', name: 'Agar Media', code: 'agar', icon: '🧫', color: 'text-purple-400 bg-purple-950/50', isActive: true },
  { id: 'default-lc', name: 'Liquid Culture', code: 'liquid_culture', icon: '💧', color: 'text-blue-400 bg-blue-950/50', isActive: true },
  { id: 'default-grain', name: 'Grain Spawn', code: 'grain_spawn', icon: '🌾', color: 'text-amber-400 bg-amber-950/50', isActive: true },
  { id: 'default-bulk', name: 'Bulk Substrate', code: 'bulk_substrate', icon: '🪵', color: 'text-emerald-400 bg-emerald-950/50', isActive: true },
  { id: 'default-casing', name: 'Casing Layer', code: 'casing', icon: '🧱', color: 'text-orange-400 bg-orange-950/50', isActive: true },
  { id: 'default-other', name: 'Other', code: 'other', icon: '📦', color: 'text-zinc-400 bg-zinc-800', isActive: true },
];

export const initialDataState: DataStoreState = {
  species: [],
  strains: initialStrains,
  locations: initialLocations,
  vessels: initialVessels,
  containerTypes: initialContainerTypes,
  substrateTypes: initialSubstrateTypes,
  suppliers: initialSuppliers,
  inventoryCategories: initialInventoryCategories,
  recipeCategories: initialRecipeCategories,
  inventoryItems: initialInventoryItems,
  cultures: initialCultures,
  grows: initialGrows,
  recipes: initialRecipes,
  settings: initialSettings,
};
